### ISSUE TITLE
STATA_BIN envrionment variable in make files

### ISSUE THREAD

**Issue by hannesdatta** [hannesdatta/tisem-airbnb#2]

**Comment by hannesdatta** [comment]
![image](https://user-images.githubusercontent.com/16557730/74238175-8b7a1400-4cd5-11ea-9449-0e8cdc86c61a.png)

**Comment by hannesdatta** [comment]
@Hulai: use STATA_BIN envrionment variable in your make files + adapt reproducible science guide to reflect the fact that we create this STATA_BIN (because now, it's still adding Stata to path)

**Comment by hulaizh** [comment]
Help me with this issue. I do not know how to set the environment variable and path in MacOS.
